### ISSUE TITLE
Installation fails on Debian 12 

### ISSUE THREAD

**Issue by JLenzy** [GoogleCloudPlatform/compute-gpu-installation#37]
**Describe the bug**
I am running a google VM with 4x T4 GPU's. When I attempt to install the appropriate drivers, the installation fails. To the best of my knowledge I am following the directions exactly as described in `readme`

**Environment**
Image: debian-12-bookworm-v20240515
Debian, Debian GNU/Linux, 12 (bookworm), amd64 built on 20240515
x86/64
GPU's: Nvidia T4

**To Reproduce**
The steps I follow:

```
mkdir -p /opt/google/cuda-installer/
cd /opt/google/cuda-installer/ || exit

sudo curl -fSsL -O https://github.com/GoogleCloudPlatform/compute-gpu-installation/releases/download/cuda-installer-v1.0.0/cuda_installer.pyz

sudo python3 cuda_installer.pyz install_cuda
Switching to working directory: /opt/google/cuda-installer
CUDA installation requires GPU driver to be installed first. Attempting to install GPU driver now.
Downloading CUDA installation kit...
Executing: sha256sum cuda_12.4.1_550.54.15_linux.run
367d2299b3a4588ab487a6d27276ca5d9ead6e394904f18bccb9e12433b9c4fb  cuda_12.4.1_550.54.15_linux.run
Installing prerequisite packages and updating kernel...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/google/cuda-installer/cuda_installer.pyz/__main__.py", line 71, in <module>
  File "/opt/google/cuda-installer/cuda_installer.pyz/os_installers/__init__.py", line 217, in install_cuda
  File "/opt/google/cuda-installer/cuda_installer.pyz/decorators.py", line 31, in wrapper
  File "/opt/google/cuda-installer/cuda_installer.pyz/os_installers/__init__.py", line 203, in _install_cuda
  File "/opt/google/cuda-installer/cuda_installer.pyz/os_installers/__init__.py", line 126, in install_driver
  File "/opt/google/cuda-installer/cuda_installer.pyz/decorators.py", line 31, in wrapper
  File "/opt/google/cuda-installer/cuda_installer.pyz/os_installers/debian.py", line 33, in _install_prerequisites
  File "/opt/google/cuda-installer/cuda_installer.pyz/os_installers/__init__.py", line 382, in run
subprocess.SubprocessError: Command exited with non-zero code

```

**Comment by m-strzelczyk** [comment]
The command that fails to execute is simple `apt update`. Can you try running it manually and see if it fails as well?

**Comment by m-strzelczyk** [comment]
I checked with my own instane with Debian 12 and 4x T4 GPU - the installation worked. Please let me know if you can manually run `apt-get update` on your system.
